### ISSUE TITLE
The password reset link included in emails is invalid

### ISSUE THREAD

**Issue by vunguyen-dmt** [overhangio/tutor-mfe#105]
The setup process for AUTHN mfe should set
AUTHN_MICROFRONTEND_DOMAIN = {{ MFE_HOST }}/{{ MYMFE_MFE_APP["name"] }}
otherwise reset password link will be: https://none/password_reset_confirm/....

**Comment by arbrandes** [comment]
Huh.  This went totally under the radar.  Indeed, we need [to set a variable for it](https://github.com/openedx/edx-platform/blob/b01cf355a7b9bf395c1e5d5ee6858b179358c4e9/openedx/core/djangoapps/user_authn/views/password_reset.py#L152), but it's not documented anywhere.
