### ISSUE TITLE
Wrong reset password link in authn mfe

### ISSUE THREAD

**Issue by vunguyen-dmt** [overhangio/tutor-mfe#112]
Reproduce:
Goto: https://apps.demo.openedx.overhang.io/authn/login
Try logging in with: username: admin, password: 123456 a few times.
The site will show a message including: "To be on the safe side, you can [reset your password](https://apps.demo.openedx.overhang.io/reset) before trying again."
the link will go to **/reset** instead of **/authn/reset/**
__
There are a few messages like that and reset password links are all the same.
This could relate to this file:
https://github.com/openedx/frontend-app-authn/blob/master/src/login/LoginFailure.jsx

**Comment by regisb** [comment]
I can confirm the reported issue. Here is a screenshot. Notice the reset link in the bottom left corner:

![Screenshot from 2023-02-21 17-11-43](https://user-images.githubusercontent.com/44319/220399410-3dfb4ccf-e00e-451f-8a73-302edd1dd29e.png)

That particular line of code looks fishy: https://github.com/openedx/frontend-app-authn/blob/open-release/olive.2/src/login/LoginFailure.jsx#L32

**Comment by johnvente** [comment]
Hello @regisb I'm a new frontend at eduNext, would you mind assigning this issue please?

**Comment by arbrandes** [comment]
@johnvente, thanks for volunteering! :)

**Comment by johnvente** [comment]
Hi guys, I wasn't able to reproduce the error. was this issue fixed already or does it continue happening? 

Here is a screenshot:


![Image](https://github.com/overhangio/tutor-mfe/assets/134975835/d97ed68b-25ef-440f-ac4f-5084aee0af1c)

**Comment by regisb** [comment]
Looks like the issue was fixed by replacing "/reset" by "reset". Compare:
https://github.com/openedx/frontend-app-authn/blob/open-release/olive.2/src/login/LoginFailure.jsx#L32
https://github.com/openedx/frontend-app-authn/blob/open-release/palm.1/src/login/LoginFailure.jsx#L34

Congrats on resolving this issue @johnvente ;)
@vunguyen-dmt if you agree, can you please close this?

**Comment by vunguyen-dmt** [comment]
Tested and it was fixed!
