### ISSUE TITLE
This repo is missing the license file

### ISSUE THREAD

**Issue by felipemontoya** [overhangio/tutor-mfe#115]
Hello there,

Other repos from the common tutor plugins list are licensed using AGP 3.0.
Should this be the same?

I found a reference saying that it is licensed using AGP (https://github.com/overhangio/tutor-mfe/issues/111#issuecomment-1425523819) but the file is missing.

If you want I can open a PR for this.

**Comment by felipemontoya** [comment]
I found it at the bottom of the readme. Sorry about the noise.

I can still add the file if you would like that.

**Comment by regisb** [comment]
Yeah, we should definitely include a LICENSE file and link to it from the README, just like other tutor plugins: https://github.com/overhangio/tutor-ecommerce/#license
Can you please open a PR @felipemontoya?
