### ISSUE TITLE
Patch instructions should use low priority for MFE settings

### ISSUE THREAD

**Issue by arbrandes** [overhangio/tutor-mfe#117]
See [this thread](https://discuss.openedx.org/t/using-mfe-config-to-set-logo-trademark-url-for-the-footer-component-in-olive/9578/2).

**Comment by regisb** [comment]
Alternatively, The MFE settings patch could itself include a specific mfe settings patch at the bottom. For instance:

```
MFE_CONFIG = {...}

{{ patch("openedx-mfe-settings") }}
```
