### ISSUE TITLE
Add a scriv-based changelog

### ISSUE THREAD

**Issue by arbrandes** [overhangio/tutor-mfe#118]
Implement a version of https://github.com/overhangio/tutor-ecommerce/pull/39 for this repository.

**Comment by regisb** [comment]
Resolved by [e9ad168e65348072a3ab29e1e69be0b6a84e92a2](https://github.com/overhangio/tutor-mfe/commit/e9ad168e65348072a3ab29e1e69be0b6a84e92a2)
