### ISSUE TITLE
Links to Account in the header are broken

### ISSUE THREAD

**Issue by snglth** [overhangio/tutor-mfe#128]
It is reproducible at demo.openedx.overhang.io
![image](https://github.com/overhangio/tutor-mfe/assets/8686360/d18fb2e5-9a57-4977-aab9-13ec7f2ebb69)

This is caused by ACCOUNT_SETTINGS_URL config variable ([link](https://github.com/openedx/frontend-component-header/blob/2543926c959c181e73d8fa61fa8baf1f58f8a48f/src/Header.jsx#L63)) not being set by tutor-mfe.

I tried to [fix it](https://github.com/snglth/tutor-mfe/commit/7caccb2d43107d1a0026c9cef77b13cef855d84e) in my fork. Works fine on `dev` environment, but not on `local` one.

**Comment by snglth** [comment]
Looks like it was fixed by #121

**Comment by regisb** [comment]
If I understand correctly, the fix that was proposed in #121 should be backported to Olive, right? Let's re-open this PR and I'll push the fix.
