### ISSUE TITLE
Bug: Required MFE-Auth variables are not defined which breaks the UI

### ISSUE THREAD

**Issue by misilot** [overhangio/tutor-mfe#139]
Both `INFO_EMAIL` and `PASSWORD_RESET_SUPPORT_LINK` are missing, and possible others from the https://github.com/openedx/frontend-app-authn documentation. 

## Missing `INFO_EMAIL`

Steps to reproduce missing `INFO_EMAIL`
1. Go to https://apps.demo.openedx.overhang.io/authn/reset?next=%2F
2. See sentence that doesn't complete, "support at"
<img width="643" alt="image" src="https://github.com/overhangio/tutor-mfe/assets/1446856/e7ff5855-ef46-470e-894c-c08df4c51c24">

If `MFE_CONFIG["INFO_EMAIL"] = "{{ CONTACT_EMAIL }}"` set via a plugin you get the following 
<img width="643" alt="image" src="https://github.com/overhangio/tutor-mfe/assets/1446856/a1e21b54-090d-4cd8-bf12-f33049da5a3e">

## Missing `PASSWORD_RESET_SUPPORT_LINK`

Without `PASSWORD_RESET_SUPPORT_LINK` the href is not generated correctly. 

<img width="1245" alt="image" src="https://github.com/overhangio/tutor-mfe/assets/1446856/7d347a6b-851d-42fc-99c2-de2feac378c4">

When `MFE_CONFIG["PASSWORD_RESET_SUPPORT_LINK"] = "mailto:{{ CONTACT_EMAIL }}"` set via a plugin you get the following:

<img width="1245" alt="image" src="https://github.com/overhangio/tutor-mfe/assets/1446856/139f7d73-c391-4c88-ad31-48101e57356f">

## Proposed Solution
Add the following to https://github.com/overhangio/tutor-mfe/blob/8522ab6adf149d27e6aeaed567795857af1c0647/tutormfe/patches/openedx-lms-production-settings#L3C1-L3C11

```
INFO_EMAIL = "{{ CONTACT_EMAIL }}
PASSWORD_RESET_SUPPORT_LINK = "mailto:{{ CONTACT_EMAIL }}"
```

@regisb if this makes sense, I can create a PR for it.

**Comment by regisb** [comment]
Yes, it does make sense, please open a PR! And please also make sure that your fix works in `tutor dev`.

**Comment by misilot** [comment]
I don't have any system to setup to use `tutor dev` unfortunately. If that will be an issue, I can attempt to get that working somewhere in the next couple of weeks
