### ISSUE TITLE
 Upgrade to Quince

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor-mfe#162]
See instructions:

https://discuss.overhang.io/t/how-to-upgrade-a-tutor-plugin/1488
overhangio/tutor#920

Don't forget to push your changes to the demo server, similar to this PR: https://github.com/overhangio/openedx-release-demo/pull/33/files

**Comment by regisb** [comment]
Good point! I rebased the quince branch on top of nightly, such that the learner dashboard should now be part of the release.

**Comment by regisb** [comment]
Yes.

**Comment by fghaas** [comment]
Gotcha, thanks!
