### ISSUE TITLE
Overhangio/openedx-learner-dashboard-dev, repository does not exist?

### ISSUE THREAD

**Issue by Silidrone** [overhangio/tutor-mfe#188]
Hi,

I am using tutor 17.0.0

I’m changing the underlying code for some of the MFEs in tutor. I changed the authn MFE successfully by forking it and then mounting my authn repo and running it in dev environment. When I try to do the same for learner-dashboard (I forked quince.1: https://github.com/openedx/frontend-app-learner-dashboard/releases/tag/open-release%2Fquince.1):

1. clone my repo
2. run `npm install` inside repo directory
3. add a mount by running `tutor mounts add "$(tutor config printroot)"/frontend-app-learner-dashboard`
4. run tutor dev launch

I get:

> docker compose -f /home/silidrone/.local/share/tutor/env/local/docker-compose.yml -f /home/silidrone/.local/share/tutor/env/dev/docker-compose.yml --project-name tutor_dev up --remove-orphans -d
> [+] Running 0/1
> ⠿ learner-dashboard Error 1.8s
> Error response from daemon: pull access denied for overhangio/openedx-learner-dashboard-dev, repository does not exist or may require ‘docker login’: denied: requested access to the resource is denied
> Error: Command failed with status 18: docker compose -f /home/silidrone/.local/share/tutor/env/local/docker-compose.yml -f /home/silidrone/.local/share/tutor/env/dev/docker-compose.yml --project-name tutor_dev up --remove-orphans -d

How am I supposed to change the code of the learner-dashboard MFE? Is this a bug or am I missing something? The exact same procedure worked for frontend-app-authn.

**Comment by Danyal-Faheem** [comment]
Hi @Silidrone, thank you for bringing this issue to our attention. This issue is due to the `learner-dashboard-dev` image on the overhangio repository. It will be fixed after #191 is merged.

For the time being, you can build the image locally first by running `tutor images build learner-dashboard-dev` and then run the `tutor dev launch` command.
