### ISSUE TITLE
tutor-mfe codebase Python 3.12 upgrade

### ISSUE THREAD

**Issue by DawoudSheraz** [overhangio/tutor-mfe#192]
- [ ] Ensure tutor-mfe codebase is compatible with Python 3.12
- [ ] Update Python to 3.12 in Dockerfile for nightly and ensure the image builds as expected. The changes would be merged to nightly  

See https://github.com/overhangio/tutor/issues/1004 for the context.

**Comment by DawoudSheraz** [comment]
@arbrandes FYI. Please let me know if you need any assistance or information. Thanks

**Comment by DawoudSheraz** [comment]
@ahmed-arb Do we need any further actions, other than CI changes?

**Comment by ahmed-arb** [comment]
No, I think thats it. After this [commit](https://github.com/overhangio/tutor-mfe/commit/50eb9d8cdcca6a19578ef1ca57968d29f25d028d) mfe plugin is compatible with python 3.12.
