### ISSUE TITLE
Error after running tutor images build mfe

### ISSUE THREAD

**Issue by allenluna** [overhangio/tutor-mfe#197]
I encountered error after running t utor images build mfe

my plugins version is:
tutor version v17.0.2

![image](https://github.com/overhangio/tutor-mfe/assets/126066409/e6296093-1918-459f-8a21-b442a884890a)

![image](https://github.com/overhangio/tutor-mfe/assets/126066409/92852ea9-b1c1-4674-94f9-53c148882ed6)

ERROR git://github.com/allenluna/VXI_Brand-OpenEdx.git#open-release/quince.2 0.6s
=> CACHED git://github.com/openedx/frontend-app-profile.git#open-release/quince.2 0.6s
=> CACHED [base 1/4] FROM [Docker](http://docker.io/library/node:18.19.0-bullseye-slim@sha256:6089d97d625bc7c3510f6c3ada72b3e80e) 0.1s
=> => resolve [Docker](http://docker.io/library/node:18.19.0-bullseye-slim@sha256:6089d97d625bc7c3510f6c3ada72b3e80e383fee52ff34) 0.1s
=> CACHED git://github.com/openedx/frontend-app-ora-grading.git#open-release/quince.2 0.6s
=> [internal] load build context 0.0s
=> CACHED git://github.com/openedx/frontend-app-learning.git#open-release/quince.2 0.6s
=> CACHED git://github.com/openedx/frontend-app-learner-dashboard.git#open-release/quince.2 0.6s
=> CACHED git://github.com/openedx/frontend-app-gradebook.git#open-release/quince.2 0.6s
=> CACHED [production 1/13] FROM [Docker](http://docker.io/library/caddy:2.7.4@sha256:505de4e957da923672a8c79f16581e9b717a2479a) 0.1s
=> => resolve [Docker](http://docker.io/library/caddy:2.7.4@sha256:505de4e957da923672a8c79f16581e9b717a2479a8d5ddb909ab2d1b351f2) 0.1s
=> CACHED git://github.com/openedx/frontend-app-discussions.git#open-release/quince.2 0.6s
=> ERROR git://github.com/openedx/frontend-app-course-authoring.git#open-release/quince.2 0.1s
=> ERROR git://github.com/openedx/frontend-app-communications.git#open-release/quince.2 0.0s
=> ERROR git://github.com/openedx/frontend-app-account.git#open-release/quince.2 0.0s
=> ERROR git://github.com/openedx/frontend-app-authn.git#open-release/quince.2 0.0s
=> [production 2/13] RUN mkdir -p /openedx/dist 0.2s
git://github.com/allenluna/VXI_Brand-OpenEdx.git#open-release/quince.2:

git://github.com/openedx/frontend-app-course-authoring.git#open-release/quince.2:

git://github.com/openedx/frontend-app-communications.git#open-release/quince.2:

git://github.com/openedx/frontend-app-account.git#open-release/quince.2:

git://github.com/openedx/frontend-app-authn.git#open-release/quince.2:

ERROR: failed to solve: failed to load cache key: repository does not contain ref open-release/quince.2, output: “”
Error: Command failed with status 1: docker buildx build --tag=[docker.io/overhangio/openedx-mfe:17.0.0-indigo](http://docker.io/overhangio/openedx-mfe:17.0.0-indigo) --no-cache --output=type=docker --cache-from=type=registry,[ref=docker.io/overhangio/openedx-mfe:17.0.0-indigo-cache](http://ref=docker.io/overhangio/openedx-mfe:17.0.0-indigo-cache) /home/itechadmin/.local/share/tutor/env/plugins/mfe/build/mfe

**Comment by Danyal-Faheem** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing
