### ISSUE TITLE
Support for ARM64

### ISSUE THREAD

**Issue by msegado** [overhangio/tutor-mfe#31]
Opening a parallel issue to https://github.com/overhangio/tutor/issues/510. I'm currently able to build on an M1 MacBook by adding a few extra build requirements and environment variables:

```diff
diff --git a/tutormfe/templates/mfe/build/mfe/Dockerfile b/tutormfe/templates/mfe/build/mfe/Dockerfile
index 726d9ca..b996eea 100644
--- a/tutormfe/templates/mfe/build/mfe/Dockerfile
+++ b/tutormfe/templates/mfe/build/mfe/Dockerfile
@@ -3,7 +3,18 @@ FROM docker.io/node:12-bullseye-slim AS base
 RUN apt update \
   && apt install -y git \
     # required for cwebp-bin
-    gcc git libgl1 libxi6 make
+    gcc git libgl1 libxi6 make \
+    # additionally required for gifsicle, mozjpeg, and optipng
+    autoconf libtool pkg-config zlib1g-dev \
+    # additionally required for node-sass
+    python g++
+
+# Required for building optipng on M1
+ENV CPPFLAGS=-DPNG_ARM_NEON_OPT=0
+
+# Required for avoiding failed frontend-app-learning build due to missing binary on M1
+# (breaks pact tests)
+ENV PACT_SKIP_BINARY_INSTALL=true
 
 RUN mkdir -p /openedx/app /openedx/env
 WORKDIR /openedx/app
```

Unfortunately, using `PACT_SKIP_BINARY_INSTALL` is a hack that will break any Pact tests, so it's not really suitable to merge in. I don't see much alternative until there's an ARM binary for Pact though. Relevant issue: pact-foundation/pact-js-core#347

**Comment by regisb** [comment]
Can we get rid of pact upstream, in Open edX?

**Comment by msegado** [comment]
Seems unlikely... it looks like they just added it this summer: https://github.com/edx/frontend-app-learning/pull/510

**Comment by regisb** [comment]
My feeling is that it's going to be easier to make a contribution to pact than to fix the issue here.

**Comment by TimothyJones** [comment]
Pact maintainer here - pact works fine on an M1 macbook running OSX because of rosetta. It won't work if you are running a different OS on that chipset, though.

**Comment by kdmccormick** [comment]
@msegado I opened a PR against frontend-app-learning to switch pact from being a base dependency to a devDependency: https://github.com/openedx/frontend-app-learning/pull/823. Do you know if that would stop Pact from breaking `npm build`? I would try myself but I'm on an Intel machine.

**Comment by kdmccormick** [comment]
It turns out that my PR linked above might fix the Pact issue for production image builds (assuming`NODE_ENV=production` when we run `npm install` for the production image), but we'd still be left with a broken build for the development image. I'm going to get it merged, but I think we'll still need an upstream Pact fix :/

**Comment by yarons** [comment]
@kdmccormick I know that there's an option to make some Dockerfile conditionals based on `BUILDTARGET` so there could be distinct pakcages for each platform (in this case an addition).

**Comment by jigsawlabs-student** [comment]
I am running into an issue with the following:
```bash
FROM docker.io/node:12-bullseye-slim AS base

RUN apt update \
  && apt install -y git \
    # required for cwebp-bin
    gcc git libgl1 libxi6 make \
    # additionally required for gifsicle, mozjpeg, and optipng
    autoconf libtool pkg-config zlib1g-dev \
    # additionally required for node-sass
    python g++
    
# Required for avoiding failed frontend-app-learning build due to missing binary on M1
# (breaks pact tests)
ENV PACT_SKIP_BINARY_INSTALL=true

RUN mkdir -p /openedx/app /openedx/env
```

However, when I run `tutor images build mfe` I get the following error:

```bash
#71 42.45 ERROR in ./src/index.scss
#71 42.45 Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
#71 42.45 ModuleBuildError: Module build failed (from ./node_modules/image-webpack-loader/index.js):
#71 42.45 Error: Cannot find module 'gifsicle'
#71 42.45 Require stack:
```

Per [suggestions](https://stackoverflow.com/questions/65147246/cannot-find-module-gifsicle-for-loading-image-webpack) on the Internet, tried updating my Dockerfile to the following to install `dh-autoreconf`, but still run into the same error:
```
RUN apt update \
  && apt install -y git \
    # required for cwebp-bin
    gcc git libgl1 libxi6 make \
    # additionally required for gifsicle, mozjpeg, and optipng
    autoconf libtool pkg-config zlib1g-dev \
    # additionally required for node-sass
    python g++
    
RUN apt-get install dh-autoreconf
```

**Comment by jigsawlabs-student** [comment]
@yarons Ok, so I *was* able to resolve this.

**Comment by yarons** [comment]
@jigsawlabs-student I just want to mention you're awesome!

Yet, I have to ask, installing some extras locally is the only solution?
(I'm asking this because of K8s mainly).

**Comment by jigsawlabs-student** [comment]
Hmm..I don't know...but glad this helped!

**Comment by regisb** [comment]
And maybe also @bradenmacdonald? thanks!
