### ISSUE TITLE
Progress issue on Learning and gradebook MFE

### ISSUE THREAD

**Issue by CodeWithEmad** [overhangio/tutor-mfe#45]
Hi

after deploying an instance of edx with tutor with Micro Frontends, everything looks fine, until one of the learners finishes one course and claims his/hers certificate, an error will be shown in the learning mfe.
![Screenshot 2022-04-17 at 14-03-29 Course Barney Stinson](https://user-images.githubusercontent.com/49523567/163716287-0e726ce3-89bd-4b61-a2b3-da9e3b9ea839.png)

the error in the logs was:  `Course Grade.Does Not Exist`

it's also said inside the [frontend-app-gradebook](https://github.com/openedx/frontend-app-gradebook#configuring-for-local-use-in-edx-platform) repo:

There are also several edx-platform waffle and feature flags you'll have to enable from the Django admin:

    Grades > Persistent grades enabled flag. Add this flag if it doesn't exist, check the enabled and enabled for all courses boxes.

I think that this part is left out. I couldn't find it in the [lms hooks](https://github.com/overhangio/tutor-mfe/blob/master/tutormfe/templates/mfe/hooks/lms/init).

How to reproduce:
create a course with some sections with a grade, and the learner must finish/answer the sections with a grade. in the progress tab, you can find the error

tutor version: 13.1.3
os: ubuntu 20.04

**Comment by BbrSofiane** [comment]
Could this be linked to this https://github.com/openedx/edx-platform/pull/29793?

**Comment by CodeWithEmad** [comment]
yes, as I said it's because the persistent grade flag will not be enabled by default after the edx instance is created and Learning MFE is enabled. I fixed it by adding that to the lms hook [here](https://github.com/overhangio/tutor-mfe/pull/48)

**Comment by BbrSofiane** [comment]
Would merging the PR above fix the issue? If it does we can make sure that it gets merged rather than adding to the lms hook.

**Comment by regisb** [comment]
If I understand correctly, either merging the PR above or merging #48 would work. I'm fine with enabling persistent grades by default on Tutor. See my comment [here](https://github.com/overhangio/tutor-mfe/pull/48#issuecomment-1110797622).

**Comment by CodeWithEmad** [comment]
closed in favor of https://github.com/overhangio/tutor-mfe/pull/48
