### ISSUE TITLE
Run failed

### ISSUE THREAD

**Issue by hijulien-gan** [overhangio/tutor-mfe#53]
After I install tutor, I run tutor plugins enable MFE. The display is normal, but when I run tutor local QuickStart again, it will fail. Refer to my post on the forum for the failure style

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Tutor forums: https://discuss.overhang.io.

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing
