### ISSUE TITLE
Custom translation does not work for Vietnamese

### ISSUE THREAD

**Issue by vunguyen-dmt** [overhangio/tutor-mfe#54]
I tried to add a custom translation for Vietnamese, I added vi.json as the guide mentioned and rebuilt the mfe image but it didn't work.
I added fr.json but with some changes to test and it worked.
It is because "vi" is not supported? If it's not, then are there ways to workaround it?.
Thanks!

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing
