### ISSUE TITLE
Bind mount is not working for the mfe apps in tutor dev mode.

### ISSUE THREAD

**Issue by dagg** [overhangio/tutor-mfe#57]
I have experienced the following problem while trying to bind-mount (using the --mount option) some of the mfe apps in tutor dev mode.

After I copy the learning mfe to a local directory:

```
tutor dev copyfrom learning /openedx/app ./frontend-app-learning
```

I try to mount the learning mfe app (according to tutor's documentation) while starting the learning app as shown below:

```
cd frontend-app-learning
tutor dev start --mount=. learning
```

and I get the following error:

```
Bind-mount: /home/user/TUTOR_DEV/frontend-app-learning -> /openedx/app in learning
docker-compose -f /home/user/.local/share/tutor/env/local/docker-compose.yml -f /home/user/.local/share/tutor/env/local/docker-compose.prod.yml -f /home/user/.local/share/tutor/env/local/docker-compose.tmp.yml --project-name tutor_local stop
ERROR: The Compose file is invalid because:
Service learning has neither an image nor a build context specified. At least one must be provided.
Error applying action 'compose:project:started': func=<function _stop_on_dev_start at 0x7fcf5dfd91b0> contexts=[]'
Error: Command failed with status 1: docker-compose -f /home/user/.local/share/tutor/env/local/docker-compose.yml -f /home/user/.local/share/tutor/env/local/docker-compose.prod.yml -f /home/user/.local/share/tutor/env/local/docker-compose.tmp.yml --project-name tutor_local stop
```

The exact same happens also with the profile app (learning and profile are the mfe apps I have tried so far).

I have to note that after I run the "copyfrom" command I have to recursively chown the directory "frontend-app-learning" because it's contents are owned by the "root" user.

Also the following command (without the "--mount" option) works perfectly:

```
tutor dev start learning
```

When I try to mount (using the --mount option) the lms or other non-mfe apps it seems to be working correctly though...

The only workaround that worked for me so far was to override the "docker-compose.yml" file by creating a "docker-compose.override.yml" file in the directory "../env/dev" ("$(tutor config printroot)/env/dev") which is a clone of the original "docker-compose.yml" that already exists in there, and put in the learning/volumes part the volume I want to be mounted when starting the learning app, like it's shown below:

```
      volumes:
          - ../plugins/mfe/apps/mfe/webpack.dev.config.js:/openedx/app/webpack.dev.config.js:ro
          - /home/user/TUTOR_DEV/frontend-app-learning:/openedx/app
```

But I guess that's not the most proper way of doing it.

I think there is a fix in a similar problem in v13.2.2 of Tutor: [Here](https://github.com/overhangio/tutor/blob/master/CHANGELOG.md#v1322-2022-05-06)

Maybe it's something similar but specific for bind mounting the mfe apps...

I use the latest (at this time) tutor version (14.0.3).

**Comment by kdmccormick** [comment]
Thanks for reporting this @dagg . It should be fixed in the latest Tutor release (v14.0.4).
