### ISSUE TITLE
The MFE apps are unavailable when Tutor runs behind a web proxy (`RUN_CADDY=false`)

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor-mfe#6]
When `RUN_CADDY=false`, there is no way to reach the Caddy service (in the MFE container) from the host.

This issue was first reported here: https://discuss.overhang.io/t/local-deployment-webproxy/1688/3 (read for more details)

**Comment by IDerr** [comment]
Hello,
I have the exact same issue during my installation, do you know if there is still a lot of work to get the PR merged ?

Thanks a lot for your work !

**Comment by regisb** [comment]
There's a little bit of work. I pinged the author of #7. Let's see if they are available.

**Comment by IDerr** [comment]
> 
> 
> There's a little bit of work. I pinged the author of #7. Let's see if they are available.

Thanks :D

**Comment by IDerr** [comment]
Thanks
