### ISSUE TITLE
Add support for frontend-app-discussions

### ISSUE THREAD

**Issue by arbrandes** [overhangio/tutor-mfe#83]
It looks like Discussions [might make it](https://github.com/openedx/platform-roadmap/issues/106#issuecomment-1309019694) after all!  Pending whether there are backports to the fixes, we should add it in, too.

- [x] https://github.com/openedx/frontend-app-discussions/pull/377
- [x] https://github.com/openedx/tcril-engineering/issues/546
- [x] https://github.com/overhangio/tutor-mfe/pull/91

**Comment by arbrandes** [comment]
Discussions is now confirmed to be in production at edx.org: https://github.com/openedx/frontend-app-discussions/pull/358#issuecomment-1325441665

**Comment by regisb** [comment]
Indeed:

![edx-discussions](https://user-images.githubusercontent.com/44319/203821524-d7359136-b0cf-4e8b-ab1d-026f9331516e.png)

**Comment by arbrandes** [comment]
[Aamir notes](https://openedx.slack.com/archives/C049JQZFR5E/p1670352928909009?thread_ts=1670352513.783809&cid=C049JQZFR5E) a known issue with legacy inline discussions vs the new MFE:

https://docs.google.com/document/d/1qj5OQAG1LsCaPVabz1AflqaYsPETXasrt4kqUufOLTU/edit#heading=h.8vdrxvgc5ofj

Not a huge deal IMHO, but I [alerted Peter](https://github.com/openedx/build-test-release-wg/issues/229#issuecomment-1340793365) to include it in the release notes.

**Comment by arbrandes** [comment]
Turns out Discussions also needs runtime config support fixes.  I submitted a PR to try and get it in:

https://github.com/openedx/frontend-app-discussions/pull/377

**Comment by arbrandes** [comment]
Done!
