### ISSUE TITLE
[k8s pod]standard_init_linux.go:228: exec user process caused: exec format error

### ISSUE THREAD

**Issue by AaronZhangL** [overhangio/tutor-mfe#84]
I build the MFE image by following command and deploy it to digitalocean k8s. but MFE pod couldn't startup, the CrashLoopBackOff error still happened.
It looks like start command in pod was failed, but I don't know how to fix this.
docker image which I used is here: `docker pull aaronzhangl/openedx-mfe:14.0.1`
```
$ kubectl get pod | grep mfe
mfe-794fc87547-9pbwx                 0/1     CrashLoopBackOff   1 (2s ago)   8s
$ kubectl logs mfe-794fc87547-9pbwx
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing
