### ISSUE TITLE
Add support for the authn MFE

### ISSUE THREAD

**Issue by arbrandes** [overhangio/tutor-mfe#90]
Upstream has implemented [a fix to the branding issue](https://github.com/openedx/frontend-app-authn/pull/681).  This might make it in as well!

- [x] https://github.com/openedx/frontend-app-authn/pull/681
- [x] https://github.com/openedx/frontend-app-authn/issues/692
- [x] https://github.com/overhangio/tutor-mfe/pull/94

**Comment by arbrandes** [comment]
We hit a brick wall for Olive: it seems the authentication API used by the Authn MFE [requires edx-enterprise](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/user_authn/views/login.py#L621) to be deployed.

Let's try again in Palm.

**Comment by arbrandes** [comment]
Turns out the presumed dependency was [a red herring](https://github.com/openedx/frontend-app-authn/issues/692#issuecomment-1344477791).  We're good to include authn again, if we want to!  I tested it, and it works.

**Comment by regisb** [comment]
It would be great if we could include all the new MFEs in the olive branch of the plugin, such that we leave some time for testers to at least have a look at the new MFEs. It's not much, but better than nothing.

**Comment by arbrandes** [comment]
@regisb, I've been rebasing tutor-mfe@olive on nightly, testing, then force-pushing as each is added, so that should be covered a few minutes after the nightly one is merged.

**Comment by arbrandes** [comment]
Aaaad we're in!
